base_url = "/"
theme = "dinkleberg"

compile_sass = true

taxonomies = [
{name = "categories", feed = true},
{name = "tags"},
]

highlight_code = true

[extra]
blog_logo = "https://user-images.githubusercontent.com/37278803/112825055-adf9f880-9061-11eb-9b5c-6542bf4040ce.png" #will appear on top header
blog_title = "PinheiroCosta" #will appear on top header after logo

## i18n words
label_tags = "Tags"
label_tag = "Tag"
label_categories = "Categorias"
label_category = "Categoria"
label_relative_posts = "Postagens Relacionadas"
label_next = "Próxima"
label_previous = "Anterior"
label_page = "Página"
label_of = "de"
label_minutes = "minutos"

og_image = "https://user-images.githubusercontent.com/37278803/112825055-adf9f880-9061-11eb-9b5c-6542bf4040ce.png" # Image that will appear on social media
og_alt_image = "Rato" # Alt for og_image
og_site_name = "PinheiroCosta" # Site Name for Open Graphic
keywords = "" # Keywords for SEO

educational_use = "knowledge share" # OPTIONAL
copyright_year = "2021" # OPTIONAL

fb_app_id = "???" # OPTIONAL, Facebook App Id to help in metrics
twitter_username = "@???" # OPTIONAL, Twitter User to help with metrics

# Sidebar automatic links
 sidebar = [
 ]
